SSH_PORT=22
CHANGE_SSH_PORT=true

DISABLE_ROOT_LOGIN=true
DISABLE_PASSWORD_AUTH=true

CREATE_ADMIN_USER=true
ADMIN_USER=admin

CONFIGURE_SSH_KEY=true

FIREWALL=ufw
CONFIGURE_FIREWALL=true

ALLOW_HTTP=true
ALLOW_HTTPS=true

ENABLE_FAIL2BAN=true
FAIL2BAN_MAX_RETRIES=5
FAIL2BAN_BAN_TIME=10

ENABLE_AUTO_UPDATES=true

ENABLE_KERNEL_HARDENING=false

ENABLE_BACKUP=true
ENABLE_AUTO_ROLLBACK=true
ROLLBACK_TIMEOUT=600

WARNING=false                                   #true/false
WARNINGSSHKEY=false
WARNINGBACKUP=true