SSH_PORT=22
CHANGE_SSH_PORT=true                            #true/false

DISABLE_ROOT_LOGIN=true                         #true/false
DISABLE_PASSWORD_AUTH=true                      #true/false

CREATE_ADMIN_USER=true                          #true/false
ADMIN_USER=admin

CONFIGURE_SSH_KEY=true                          #true/false

FIREWALL=ufw
CONFIGURE_FIREWALL=true                         #true/false

ALLOW_HTTP=true                                 #true/false
ALLOW_HTTPS=true                                #true/false

ENABLE_FAIL2BAN=true                            #true/false
FAIL2BAN_MAX_RETRIES=5
FAIL2BAN_BAN_TIME=10

ENABLE_AUTO_UPDATES=true                        #true/false

ENABLE_KERNEL_HARDENING=false                   #true/false

ENABLE_BACKUP=true                              #true/false
ENABLE_AUTO_ROLLBACK=true                       #true/false
ROLLBACK_TIMEOUT=600

WARNING=false                                   #true/false
WARNINGSSHKEY=false                             #true/false
WARNINGBACKUP=true                              #true/false