SSH_PORT=22                                     #free ssh port                              #optional
CHANGE_SSH_PORT=true                            #true/false                                 #optional

DISABLE_ROOT_LOGIN=true                         #true/false                                 #optional
DISABLE_PASSWORD_AUTH=true                      #true/false                                 #optional

CREATE_ADMIN_USER=true                          #true/false                                 #optional
ADMIN_USER=admin                                #empty or name                              #optional

CONFIGURE_SSH_KEY=true                          #true/false                                 #optional

FIREWALL=ufw                                    #ufw/iptables/firewalld/nftables            #optional
CONFIGURE_FIREWALL=true                         #true/false                                 #optional

ALLOW_HTTP=true                                 #true/false                                 #not optional
ALLOW_HTTPS=true                                #true/false                                 #not optional

ENABLE_FAIL2BAN=true                            #true/false                                 #optional
FAIL2BAN_MAX_RETRIES=5                          #number                                     #optional
FAIL2BAN_BAN_TIME=10                            #number in mins                             #optional
FAIL2BAN_FIND_TIME=10

ENABLE_AUTO_UPDATES=true                        #true/false                                 #optional

ENABLE_KERNEL_HARDENING=false                   #true/false                                 #optional

ENABLE_BACKUP=true                              #true/false                                 #optional
ENABLE_AUTO_ROLLBACK=true                       #true/false                                 #optional
ROLLBACK_TIMEOUT=600                            #number in seconds                          #optional

WARNING=true                                    #true/false                                 #optional
WARNINGSSHKEY=true                              #true/false                                 #optional
WARNINGBACKUP=true                              #true/false                                 #optional